<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://Service.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://Service.com" xmlns:intf="http://Service.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:portType name="Service">

   </wsdl:portType>

   <wsdl:binding name="ServiceSoapBinding" type="impl:Service">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

   </wsdl:binding>

   <wsdl:service name="ServiceService">

      <wsdl:port binding="impl:ServiceSoapBinding" name="Service">

         <wsdlsoap:address location="http://localhost:8010/WS_Transmetro/services/Service"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
